### ISSUE TITLE
Refactor all packages and docs to suit our project better

### ISSUE THREAD

**Issue by Jaspertzx** [AY2324S2-CS2103T-T09-2/tp#65]
# Big Refactor

Update the following, including
    - [ ] docs
    - [ ] code
    - [ ] [Main page](https://ay2324s2-cs2103t-t09-2.github.io/tp/)
    - [ ] [UG](https://ay2324s2-cs2103t-t09-2.github.io/tp/UserGuide.html)
    - [ ] [DG](https://ay2324s2-cs2103t-t09-2.github.io/tp/DeveloperGuide.html)
    - [ ] README.md

- [ ] Change all `Person` instances to `Client`
    - [ ] docs
    - [ ] code
    - [ ] [Main page](https://ay2324s2-cs2103t-t09-2.github.io/tp/)
    - [ ] [UG](https://ay2324s2-cs2103t-t09-2.github.io/tp/UserGuide.html)
    - [ ] [DG](https://ay2324s2-cs2103t-t09-2.github.io/tp/DeveloperGuide.html)
    - [ ] README.md

- [ ] Change all `addressbook.json` instances to `crm.json`
     - [ ] docs 
     - [ ] code
     - [ ] [Main page](https://ay2324s2-cs2103t-t09-2.github.io/tp/)
     - [ ] [UG](https://ay2324s2-cs2103t-t09-2.github.io/tp/UserGuide.html)
     - [ ] [DG](https://ay2324s2-cs2103t-t09-2.github.io/tp/DeveloperGuide.html)
     - [ ] README.md

These should be changed to to reflect our project better.

Should be done last to avoid too many conflicts during merging.

**Comment by rertyy** [comment]
To do #180
